openapi: "3.0.0"
info:
  version: 0.1.0
  title: wallet open API
  description: zkws API
  license:
    name: MIT
servers:
  - url: http://localhost:3000/v1
paths:
  /test:
    get:
      tags:
        - "root"
      summary: "Test endpoint"
      operationId: "test"
      produces:
      - "application/json"
      responses:
        200:
          description: "success"

  /basket/link:
    get:
      tags:
        - "root"
      summary: "BasketLink endpoint"
      operationId: "basketLink"
      produces:
      - "application/json"
      responses:
        200:
          description: "success"

  /basket/view/{basketId}:
    get:
      tags:
        - "root"
      summary: "Basket endpoint"
      operationId: "basket"
      parameters:
        - in: path
          name: basketId
          required: true
          schema:
            type: string
          description: basket id to retrieve
      produces:
      - "application/json"
      responses:
        200:
          description: "success"

