openapi: "3.0.0"
info:
  title: wallet open API
  version: 0.1.0
  description: zkws opan API
  license:
    name: MIT
servers:
  - url: http://localhost:3000
  - url: http://localhost:3000/v1
paths:
  /test:
    get:
      operationId: "test"
      summary: "Test endpoint"
      tags:
        - "root"
      responses:
        200:
          description: A test request
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    status:
                      type: number 
                      example: 200
                    salary:
                      type: string
                      example: "default message string"

  /basket/link:
    get:
      tags:
        - "root"
      summary: "BasketLink endpoint"
      operationId: "basketLink"
      responses:
        200:
          description: "success"
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    status:
                      type: number 
                      example: 200
                    salary:
                      type: string
                      example: "default message string"

  /basket/view/{basketId}:
    get:
      tags:
        - "root"
      summary: "Basket endpoint"
      operationId: "basket"
      parameters:
        - in: path
          name: basketId
          required: true
          schema:
            type: string
          description: basket id to retrieve
      responses:
        200:
          description: "success"
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    status:
                      type: number 
                      example: 200
                    salary:
                      type: string
                      example: "default message string"

